function classes = getClassNames()
%     classes = ['applered   '; 'appleyellow'; 'applegreen '; 'banana     '; 'fries      '; ...
%                'strawberry '; 'tomato     '; 'salad      '; 'rice       '; 'broccoli   '; ...
%                'burger     '; 'hotdog     '; 'pasta      '; 'pizza      '; 'egg        '; ...
%                'cookie     '];
    classes = ['applered   '; 'appleyellow'; 'applegreen '; 'banana     '; 'fries      '; ...
               'strawberry '; 'tomato     '; 'salad      '; 'rice       '; 'broccoli   '; ...
               'burger     '; 'pizza      '];
    classes = cellstr(classes);
end