function classes = getClassNames()
    classes = ['applered   '; 'appleyellow'; 'applegreen '; 'eggshell   '; 'egg        ';...
               'strawberry '; 'tomato     '; 'salad      '; 'rice       '; 'broccoli   '; ...
               'burger     '; 'hotdog     '; 'pasta      '; 'pizza      '; ...
               'banana     '; 'fries      '; 'cookie     '];
%     classes = ['applered   '; 'appleyellow'; 'applegreen '; 'banana     '; 'fries      '; ...
%                'strawberry '; 'tomato     '; 'salad      '; 'rice       '; 'broccoli   '; ...
%                'burger     '; 'pizza      '];
    classes = cellstr(classes);
end